<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--[if lt IE 7 ]>
<html lang="<?php echo $this->getLang() ?>" xml:lang="<?php echo $this->getLang() ?>" class="ie6"><![endif]-->
<!--[if IE 7 ]>
<html lang="<?php echo $this->getLang() ?>" xml:lang="<?php echo $this->getLang() ?>" class="ie7"><![endif]-->
<!--[if IE 8 ]>
<html lang="<?php echo $this->getLang() ?>" xml:lang="<?php echo $this->getLang() ?>" class="ie8"><![endif]-->
<!--[if IE 9 ]>
<html lang="<?php echo $this->getLang() ?>" xml:lang="<?php echo $this->getLang() ?>" class="ie9"><![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html lang="<?php echo $this->getLang() ?>" xml:lang="<?php echo $this->getLang() ?>" class="no-js"><!--<![endif]-->
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
    <?php echo $this->getChildHtml('global_messages') ?>
    <?php echo $this->getChildHtml('content') ?>

    <?php //echo $this->getChildHtml('footer') ?>
    <?php //echo $this->getChildHtml('before_body_end') ?>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
