<?php /*
<div class="footer-container">
    <div class="footer">
        <?php echo $this->getChildHtml() ?>
        <p class="bugs"><?php echo $this->__('Help Us to Keep Magento Healthy') ?> - <a href="http://www.magentocommerce.com/bug-tracking" onclick="this.target='_blank'"><strong><?php echo $this->__('Report All Bugs') ?></strong></a> <?php echo $this->__('(ver. %s)', Mage::getVersion()) ?></p>
        <address><?php echo $this->getCopyright() ?></address>
    </div>
</div>
 */ ?>

<div class="footer">
    <h3>Approved as Dietary Supplements in EU according to regulation</h3>
    <div class="col2-set">
        <div class="col-1">
            <h4>About us</h4>
            <p>Natural Pharma Group Ltd develop highly effective dietary supplements based on scientific research on natural raw materials.</p>
            <p>NPG develop these fine herbs, vitamin and minerals into potent natural Dietary Supplements without having them addressed as pharmaceutical.</p>
            <p>NPG act as a link between scientific research and material development into potent supplements thus make these amazing new product and combinations available to our customers.</p>
        </div>
        <div class="col-2">
            <h4>Disclaimer</h4>
            <p>Natural Pharma Group Ltd deal solely in natural Dietary supplements as an effective alternative to pharmaceutical medicines.</p>
            <p>Research based and highly effective ingredients are our specialty.</p>
            <p>Dietary supplement shall not replace a regular healthy diet. </p>
            <p>Products shall be stored out of reach of children. Pregnant or nursing women shall not use dietary supplements without supervision.</p>
            <p>We advice always contact your doctor before starting any supplement regime.</p>
        </div>
    </div>
	<dl>
		<dt>Epost:</dt>
		<dd><a href="mailto:service@naturalpharmagroup.com">service@naturalpharmagroup.com</a></dd>
		<dt>Telefon:</dt>
		<dd> +47 21619666 (Åpent 08.00 – 16.00)</dd>
	</dl>
</div>
